# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        my_config:
            extraPlugins: "justify"
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    plugins:
        justify:
            path: "/build/ckeditor/extra-plugins/justify/"
            filename: "plugin.js"
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
