framework:
    workflows:
        articles_reservation:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Article
            initial_marking: draft
            places:
                - draft
                - online
                - reserved
                - received
            transitions:
                to_draft:
                    guard: is_granted('ROLE_ADMIN')
                    from: online
                    to: draft
                to_online:
                    guard: is_granted('ROLE_ADMIN')
                    from: draft
                    to: online
                to_reserved:
                    from: online
                    to: reserved
                clear_reservation:
                    from: reserved
                    to: online
                to_received:
                    guard: is_granted('ROLE_ADMIN')
                    from: reserved
                    to: received
