name: Php-cs-fixer

on:
    push:
        branches: [ main ]
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'

            - name: Run php-cs-fixer in dry-run mode
              run: |
                  cd app
                  composer install --working-dir=tools/php-cs-fixer --prefer-dist --no-progress --no-suggest
                  tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run
