name: PHP Unit

on:
    push:
        branches: [ main, develop ]
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: imagick, swoole

            - name: Install Dependencies
              run: |
                  cd app
                  composer install --prefer-dist --no-interaction --no-progress

            - name: Init Database
              run: |
                  cd app
                  php bin/console doctrine:database:drop --force --env=test
                  php bin/console doctrine:database:create --env=test
                  php bin/console d:sc:up --force --env=test
                  php bin/console d:f:l --env=test -n

            - name: Run PHPUnit
              run: |
                  cd app
                  php bin/phpunit --configuration phpunit.xml.dist
